---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  type: ClusterIP
  selector:
    app: collector
  ports:
  - name: zpages
    port: 55679
    targetPort: 55679
  - name: http
    port: 4317
    targetPort: 4317
