resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: apiservice-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - MY_PARAMETER=MyAspirateParameterValue
    - MY_SECRET_PARAMETER=secretParam
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
- name: apiservice-secrets
  envs:
  - .apiservice.secrets
